// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AnalyzeResponse
 */
export type AnalyzeResponse = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    explanation: ExplanationResponse;
    debugging: DebuggingResponse;
    suggestions: SuggestionsResponse;
    /**
     * Analysis Time Ms
     */
    analysis_time_ms?: number | null;
};

/**
 * AuthResponse
 *
 * Response returned after successful authentication.
 *
 * Attributes:
 * access_token: JWT bearer token for authenticated requests.
 * user_id: Internal numeric user identifier.
 * email: The user's email address.
 */
export type AuthResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Email
     */
    email: string;
};

/**
 * Body_analyze_zip_analyze_zip__post
 */
export type BodyAnalyzeZipAnalyzeZipPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_file_upload_validate_post
 */
export type BodyUploadFileUploadValidatePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChatMessageRequest
 */
export type ChatMessageRequest = {
    /**
     * Message
     */
    message: string;
    /**
     * Code
     */
    code?: string | null;
    /**
     * History
     */
    history?: Array<string>;
    /**
     * Level
     */
    level?: string;
};

/**
 * ChatMessageResponse
 */
export type ChatMessageResponse = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * Mode
     */
    mode: string;
    /**
     * Reply
     */
    reply: string;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Message
     */
    message: string;
    /**
     * Code
     */
    code?: string | null;
    /**
     * History
     */
    history?: Array<string>;
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Response
     */
    response: string;
};

/**
 * CodeRequest
 */
export type CodeRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * Language
     */
    language?: string | null;
};

/**
 * DebuggingResponse
 */
export type DebuggingResponse = {
    /**
     * Issues
     */
    issues: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Summary
     */
    summary: string;
    /**
     * Clean
     */
    clean: boolean;
    /**
     * Error Count
     */
    error_count: number;
    /**
     * Warning Count
     */
    warning_count: number;
    /**
     * Info Count
     */
    info_count: number;
    /**
     * Code
     */
    code: string;
};

/**
 * ExplanationResponse
 */
export type ExplanationResponse = {
    /**
     * Language
     */
    language: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Key Points
     */
    key_points: Array<string>;
    /**
     * Complexity
     */
    complexity: string;
    /**
     * Line Count
     */
    line_count: number;
    /**
     * Function Count
     */
    function_count: number;
    /**
     * Class Count
     */
    class_count: number;
    /**
     * Cyclomatic Complexity
     */
    cyclomatic_complexity: number;
    /**
     * Complexity Risk
     */
    complexity_risk: string;
};

/**
 * FavoriteCreateRequest
 */
export type FavoriteCreateRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Action
     */
    action: string;
    /**
     * Code
     */
    code: string;
    /**
     * Result Json
     */
    result_json: string;
};

/**
 * FavoriteRecord
 */
export type FavoriteRecord = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Action
     */
    action: string;
    /**
     * Code
     */
    code: string;
    /**
     * Result Json
     */
    result_json: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Version
     */
    version: string;
    /**
     * Message
     */
    message: string;
    /**
     * Endpoints
     */
    endpoints?: Array<string> | null;
};

/**
 * HistoryCreateRequest
 */
export type HistoryCreateRequest = {
    /**
     * Action
     */
    action: string;
    /**
     * Code
     */
    code: string;
    /**
     * Result Json
     */
    result_json: string;
};

/**
 * HistoryEntry
 */
export type HistoryEntry = {
    /**
     * Id
     */
    id: number;
    /**
     * Code Hash
     */
    code_hash: string;
    /**
     * Language
     */
    language: string;
    /**
     * Score
     */
    score: number | null;
    /**
     * Issue Count
     */
    issue_count: number | null;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Code Preview
     */
    code_preview: string;
};

/**
 * HistoryRecord
 */
export type HistoryRecord = {
    /**
     * Id
     */
    id: number;
    /**
     * Action
     */
    action: string;
    /**
     * Code
     */
    code: string;
    /**
     * Result Json
     */
    result_json: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HistorySaveRequest
 */
export type HistorySaveRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * Language
     */
    language: string;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Issue Count
     */
    issue_count?: number | null;
};

/**
 * LivenessResponse
 *
 * Minimal liveness response — emitted only when the process can answer.
 */
export type LivenessResponse = {
    /**
     * Status
     */
    status: string;
};

/**
 * LoginRequest
 *
 * Request body for user login.
 *
 * Attributes:
 * email: The user's email address.
 * password: The user's password.
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ReadinessResponse
 *
 * Readiness response with a per-dependency breakdown.
 *
 * ``status`` is ``"ok"`` only when every entry in ``checks`` has ``ok=True``.
 * Each ``checks`` entry contains at minimum ``ok`` (bool) and ``elapsed_ms``
 * (float), plus an optional ``error`` field when the check failed.
 */
export type ReadinessResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Checks
     */
    checks: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

/**
 * ShareCreateRequest
 */
export type ShareCreateRequest = {
    /**
     * Action
     */
    action?: string;
    /**
     * Code
     */
    code: string;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Result Json
     */
    result_json?: string | null;
};

/**
 * ShareRecord
 */
export type ShareRecord = {
    /**
     * Id
     */
    id: string;
    /**
     * Action
     */
    action: string;
    /**
     * Code
     */
    code: string;
    /**
     * Result
     */
    result: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SignupRequest
 *
 * Request body for creating a new user account.
 *
 * Attributes:
 * email: The user's email address.
 * password: The user's chosen password (plaintext in request).
 */
export type SignupRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * SubscribeRequest
 */
export type SubscribeRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * SubscribeResponse
 */
export type SubscribeResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Email
     */
    email: string;
};

/**
 * Suggestion
 */
export type Suggestion = {
    /**
     * Category
     */
    category: string;
    /**
     * Description
     */
    description: string;
    /**
     * Line Number
     */
    line_number?: number | null;
    /**
     * Line Range
     */
    line_range?: Array<number> | null;
    /**
     * Code Context
     */
    code_context?: string | null;
    /**
     * Example
     */
    example?: string | null;
    /**
     * Priority
     */
    priority: string;
};

/**
 * SuggestionsResponse
 */
export type SuggestionsResponse = {
    /**
     * Suggestions
     */
    suggestions: Array<Suggestion>;
    /**
     * Overall Score
     */
    overall_score: number;
    /**
     * Grade
     */
    grade: string;
    /**
     * Next Step
     */
    next_step: string;
};

/**
 * UnsubscribeRequest
 */
export type UnsubscribeRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Token
     */
    token: string;
};

/**
 * UserProfileResponse
 *
 * Public user profile returned by `/auth/me`.
 *
 * Attributes:
 * user_id: Internal numeric user identifier.
 * email: The user's email address.
 */
export type UserProfileResponse = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Email
     */
    email: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ZipAnalyzeFileResult
 */
export type ZipAnalyzeFileResult = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Language
     */
    language: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    analysis: AnalyzeResponse;
};

/**
 * ZipAnalyzeResponse
 */
export type ZipAnalyzeResponse = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * File Count
     */
    file_count: number;
    /**
     * Total Size Bytes
     */
    total_size_bytes: number;
    /**
     * Overall Project Score
     */
    overall_project_score: number;
    /**
     * Grade
     */
    grade: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Files
     */
    files: Array<ZipAnalyzeFileResult>;
    /**
     * Skipped Files
     */
    skipped_files?: Array<string>;
    /**
     * Analysis Time Ms
     */
    analysis_time_ms?: number | null;
};

export type ExplainExplanationPostData = {
    body: CodeRequest;
    path?: never;
    query?: never;
    url: '/explanation/';
};

export type ExplainExplanationPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExplainExplanationPostError = ExplainExplanationPostErrors[keyof ExplainExplanationPostErrors];

export type ExplainExplanationPostResponses = {
    /**
     * Successful Response
     */
    200: ExplanationResponse;
};

export type ExplainExplanationPostResponse = ExplainExplanationPostResponses[keyof ExplainExplanationPostResponses];

export type DebugDebuggingPostData = {
    body: CodeRequest;
    path?: never;
    query?: never;
    url: '/debugging/';
};

export type DebugDebuggingPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DebugDebuggingPostError = DebugDebuggingPostErrors[keyof DebugDebuggingPostErrors];

export type DebugDebuggingPostResponses = {
    /**
     * Successful Response
     */
    200: DebuggingResponse;
};

export type DebugDebuggingPostResponse = DebugDebuggingPostResponses[keyof DebugDebuggingPostResponses];

export type SuggestSuggestionsPostData = {
    body: CodeRequest;
    path?: never;
    query?: never;
    url: '/suggestions/';
};

export type SuggestSuggestionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SuggestSuggestionsPostError = SuggestSuggestionsPostErrors[keyof SuggestSuggestionsPostErrors];

export type SuggestSuggestionsPostResponses = {
    /**
     * Successful Response
     */
    200: SuggestionsResponse;
};

export type SuggestSuggestionsPostResponse = SuggestSuggestionsPostResponses[keyof SuggestSuggestionsPostResponses];

export type AnalyzeStreamGetAnalyzeStreamGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         *
         * Source code to analyze
         */
        code: string;
        /**
         * Language
         *
         * Optional language hint
         */
        language?: string | null;
    };
    url: '/analyze/stream';
};

export type AnalyzeStreamGetAnalyzeStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeStreamGetAnalyzeStreamGetError = AnalyzeStreamGetAnalyzeStreamGetErrors[keyof AnalyzeStreamGetAnalyzeStreamGetErrors];

export type AnalyzeStreamGetAnalyzeStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AnalyzeStreamAnalyzeStreamPostData = {
    body: CodeRequest;
    path?: never;
    query?: never;
    url: '/analyze/stream';
};

export type AnalyzeStreamAnalyzeStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeStreamAnalyzeStreamPostError = AnalyzeStreamAnalyzeStreamPostErrors[keyof AnalyzeStreamAnalyzeStreamPostErrors];

export type AnalyzeStreamAnalyzeStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AnalyzeAnalyzePostData = {
    body: CodeRequest;
    path?: never;
    query?: never;
    url: '/analyze/';
};

export type AnalyzeAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeAnalyzePostError = AnalyzeAnalyzePostErrors[keyof AnalyzeAnalyzePostErrors];

export type AnalyzeAnalyzePostResponses = {
    /**
     * Successful Response
     */
    200: AnalyzeResponse;
};

export type AnalyzeAnalyzePostResponse = AnalyzeAnalyzePostResponses[keyof AnalyzeAnalyzePostResponses];

export type AnalyzeZipAnalyzeZipPostData = {
    body: BodyAnalyzeZipAnalyzeZipPost;
    path?: never;
    query?: never;
    url: '/analyze/zip/';
};

export type AnalyzeZipAnalyzeZipPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeZipAnalyzeZipPostError = AnalyzeZipAnalyzeZipPostErrors[keyof AnalyzeZipAnalyzeZipPostErrors];

export type AnalyzeZipAnalyzeZipPostResponses = {
    /**
     * Successful Response
     */
    200: ZipAnalyzeResponse;
};

export type AnalyzeZipAnalyzeZipPostResponse = AnalyzeZipAnalyzeZipPostResponses[keyof AnalyzeZipAnalyzeZipPostResponses];

export type SubscribeSubscribePostData = {
    body: SubscribeRequest;
    path?: never;
    query?: never;
    url: '/subscribe/';
};

export type SubscribeSubscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscribeSubscribePostError = SubscribeSubscribePostErrors[keyof SubscribeSubscribePostErrors];

export type SubscribeSubscribePostResponses = {
    /**
     * Successful Response
     */
    200: SubscribeResponse;
};

export type SubscribeSubscribePostResponse = SubscribeSubscribePostResponses[keyof SubscribeSubscribePostResponses];

export type UnsubscribeViaGetSubscribeUnsubscribeGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
        /**
         * Token
         */
        token: string;
    };
    url: '/subscribe/unsubscribe';
};

export type UnsubscribeViaGetSubscribeUnsubscribeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnsubscribeViaGetSubscribeUnsubscribeGetError = UnsubscribeViaGetSubscribeUnsubscribeGetErrors[keyof UnsubscribeViaGetSubscribeUnsubscribeGetErrors];

export type UnsubscribeViaGetSubscribeUnsubscribeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UnsubscribeSubscribeUnsubscribePostData = {
    body: UnsubscribeRequest;
    path?: never;
    query?: never;
    url: '/subscribe/unsubscribe';
};

export type UnsubscribeSubscribeUnsubscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnsubscribeSubscribeUnsubscribePostError = UnsubscribeSubscribeUnsubscribePostErrors[keyof UnsubscribeSubscribeUnsubscribePostErrors];

export type UnsubscribeSubscribeUnsubscribePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetHistoryHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/history/';
};

export type GetHistoryHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHistoryHistoryGetError = GetHistoryHistoryGetErrors[keyof GetHistoryHistoryGetErrors];

export type GetHistoryHistoryGetResponses = {
    /**
     * Response Get History History  Get
     *
     * Successful Response
     */
    200: Array<HistoryEntry>;
};

export type GetHistoryHistoryGetResponse = GetHistoryHistoryGetResponses[keyof GetHistoryHistoryGetResponses];

export type SaveHistoryHistoryPostData = {
    body: HistorySaveRequest;
    path?: never;
    query?: never;
    url: '/history/';
};

export type SaveHistoryHistoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveHistoryHistoryPostError = SaveHistoryHistoryPostErrors[keyof SaveHistoryHistoryPostErrors];

export type SaveHistoryHistoryPostResponses = {
    /**
     * Response Save History History  Post
     *
     * Successful Response
     */
    201: {
        [key: string]: unknown;
    };
};

export type SaveHistoryHistoryPostResponse = SaveHistoryHistoryPostResponses[keyof SaveHistoryHistoryPostResponses];

export type SearchHistoryHistorySearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/history/search';
};

export type SearchHistoryHistorySearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchHistoryHistorySearchGetError = SearchHistoryHistorySearchGetErrors[keyof SearchHistoryHistorySearchGetErrors];

export type SearchHistoryHistorySearchGetResponses = {
    /**
     * Response Search History History Search Get
     *
     * Successful Response
     */
    200: Array<HistoryEntry>;
};

export type SearchHistoryHistorySearchGetResponse = SearchHistoryHistorySearchGetResponses[keyof SearchHistoryHistorySearchGetResponses];

export type DeleteHistoryHistoryEntryIdDeleteData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: number;
    };
    query?: never;
    url: '/history/{entry_id}';
};

export type DeleteHistoryHistoryEntryIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteHistoryHistoryEntryIdDeleteError = DeleteHistoryHistoryEntryIdDeleteErrors[keyof DeleteHistoryHistoryEntryIdDeleteErrors];

export type DeleteHistoryHistoryEntryIdDeleteResponses = {
    /**
     * Response Delete History History  Entry Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteHistoryHistoryEntryIdDeleteResponse = DeleteHistoryHistoryEntryIdDeleteResponses[keyof DeleteHistoryHistoryEntryIdDeleteResponses];

export type SignupAuthSignupPostData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type SignupAuthSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupAuthSignupPostError = SignupAuthSignupPostErrors[keyof SignupAuthSignupPostErrors];

export type SignupAuthSignupPostResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type SignupAuthSignupPostResponse = SignupAuthSignupPostResponses[keyof SignupAuthSignupPostResponses];

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type MeAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type MeAuthMeGetResponse = MeAuthMeGetResponses[keyof MeAuthMeGetResponses];

export type ChatChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat';
};

export type ChatChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatChatPostError = ChatChatPostErrors[keyof ChatChatPostErrors];

export type ChatChatPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatChatPostResponse = ChatChatPostResponses[keyof ChatChatPostResponses];

export type ChatMessageChatMessagePostData = {
    body: ChatMessageRequest;
    path?: never;
    query?: never;
    url: '/chat/message';
};

export type ChatMessageChatMessagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatMessageChatMessagePostError = ChatMessageChatMessagePostErrors[keyof ChatMessageChatMessagePostErrors];

export type ChatMessageChatMessagePostResponses = {
    /**
     * Successful Response
     */
    200: ChatMessageResponse;
};

export type ChatMessageChatMessagePostResponse = ChatMessageChatMessagePostResponses[keyof ChatMessageChatMessagePostResponses];

export type CreateShareSharePostData = {
    body: ShareCreateRequest;
    path?: never;
    query?: never;
    url: '/share/';
};

export type CreateShareSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateShareSharePostError = CreateShareSharePostErrors[keyof CreateShareSharePostErrors];

export type CreateShareSharePostResponses = {
    /**
     * Successful Response
     */
    200: ShareRecord;
};

export type CreateShareSharePostResponse = CreateShareSharePostResponses[keyof CreateShareSharePostResponses];

export type GetShareShareTokenGetData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/share/{token}';
};

export type GetShareShareTokenGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShareShareTokenGetError = GetShareShareTokenGetErrors[keyof GetShareShareTokenGetErrors];

export type GetShareShareTokenGetResponses = {
    /**
     * Successful Response
     */
    200: ShareRecord;
};

export type GetShareShareTokenGetResponse = GetShareShareTokenGetResponses[keyof GetShareShareTokenGetResponses];

export type ClearHistoryUserHistoryDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/history';
};

export type ClearHistoryUserHistoryDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListHistoryUserHistoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/history';
};

export type ListHistoryUserHistoryGetResponses = {
    /**
     * Response List History User History Get
     *
     * Successful Response
     */
    200: Array<HistoryRecord>;
};

export type ListHistoryUserHistoryGetResponse = ListHistoryUserHistoryGetResponses[keyof ListHistoryUserHistoryGetResponses];

export type CreateHistoryUserHistoryPostData = {
    body: HistoryCreateRequest;
    path?: never;
    query?: never;
    url: '/user/history';
};

export type CreateHistoryUserHistoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateHistoryUserHistoryPostError = CreateHistoryUserHistoryPostErrors[keyof CreateHistoryUserHistoryPostErrors];

export type CreateHistoryUserHistoryPostResponses = {
    /**
     * Successful Response
     */
    200: HistoryRecord;
};

export type CreateHistoryUserHistoryPostResponse = CreateHistoryUserHistoryPostResponses[keyof CreateHistoryUserHistoryPostResponses];

export type DeleteHistoryUserHistoryHistoryIdDeleteData = {
    body?: never;
    path: {
        /**
         * History Id
         */
        history_id: number;
    };
    query?: never;
    url: '/user/history/{history_id}';
};

export type DeleteHistoryUserHistoryHistoryIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteHistoryUserHistoryHistoryIdDeleteError = DeleteHistoryUserHistoryHistoryIdDeleteErrors[keyof DeleteHistoryUserHistoryHistoryIdDeleteErrors];

export type DeleteHistoryUserHistoryHistoryIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClearFavoritesUserFavoritesDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/favorites';
};

export type ClearFavoritesUserFavoritesDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListFavoritesUserFavoritesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/favorites';
};

export type ListFavoritesUserFavoritesGetResponses = {
    /**
     * Response List Favorites User Favorites Get
     *
     * Successful Response
     */
    200: Array<FavoriteRecord>;
};

export type ListFavoritesUserFavoritesGetResponse = ListFavoritesUserFavoritesGetResponses[keyof ListFavoritesUserFavoritesGetResponses];

export type CreateFavoriteUserFavoritesPostData = {
    body: FavoriteCreateRequest;
    path?: never;
    query?: never;
    url: '/user/favorites';
};

export type CreateFavoriteUserFavoritesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFavoriteUserFavoritesPostError = CreateFavoriteUserFavoritesPostErrors[keyof CreateFavoriteUserFavoritesPostErrors];

export type CreateFavoriteUserFavoritesPostResponses = {
    /**
     * Successful Response
     */
    200: FavoriteRecord;
};

export type CreateFavoriteUserFavoritesPostResponse = CreateFavoriteUserFavoritesPostResponses[keyof CreateFavoriteUserFavoritesPostResponses];

export type DeleteFavoriteUserFavoritesFavoriteIdDeleteData = {
    body?: never;
    path: {
        /**
         * Favorite Id
         */
        favorite_id: number;
    };
    query?: never;
    url: '/user/favorites/{favorite_id}';
};

export type DeleteFavoriteUserFavoritesFavoriteIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFavoriteUserFavoritesFavoriteIdDeleteError = DeleteFavoriteUserFavoritesFavoriteIdDeleteErrors[keyof DeleteFavoriteUserFavoritesFavoriteIdDeleteErrors];

export type DeleteFavoriteUserFavoritesFavoriteIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type IndexUploadUploadGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/upload/';
};

export type IndexUploadUploadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFileUploadValidatePostData = {
    body: BodyUploadFileUploadValidatePost;
    path?: never;
    query?: never;
    url: '/upload/validate';
};

export type UploadFileUploadValidatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileUploadValidatePostError = UploadFileUploadValidatePostErrors[keyof UploadFileUploadValidatePostErrors];

export type UploadFileUploadValidatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LivenessHealthzLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz/live';
};

export type LivenessHealthzLiveGetResponses = {
    /**
     * Successful Response
     */
    200: LivenessResponse;
};

export type LivenessHealthzLiveGetResponse = LivenessHealthzLiveGetResponses[keyof LivenessHealthzLiveGetResponses];

export type ReadinessHealthzReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz/ready';
};

export type ReadinessHealthzReadyGetErrors = {
    /**
     * One or more dependency checks failed.
     */
    503: ReadinessResponse;
};

export type ReadinessHealthzReadyGetError = ReadinessHealthzReadyGetErrors[keyof ReadinessHealthzReadyGetErrors];

export type ReadinessHealthzReadyGetResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type ReadinessHealthzReadyGetResponse = ReadinessHealthzReadyGetResponses[keyof ReadinessHealthzReadyGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type PingPingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping';
};

export type PingPingGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
